path: ./
jobs: 10
cache: .phplint-cache
extensions:
  - php

exclude:
  - vendor

finder:
  include:
    - "*.php"
  exclude:
    - "vendor/"
    - "coverage/"
    - ".git/"
    - "*.cache"

warning: false
memory-limit: -1
